[binaries]
c = 'ppu-gcc'
cpp = 'ppu-g++'
ar = 'ppu-ar'
strip = 'ppu-strip'
# Idiomatic Meson way to override pkg-config environment variables for a cross-target
pkg-config = ['env', 'PKG_CONFIG_DIR=', 'PKG_CONFIG_PATH=', 'PKG_CONFIG_SYSROOT_DIR=', 'PKG_CONFIG_LIBDIR=/usr/local/ps3dev/portlibs/ppu/lib/pkgconfig', 'pkg-config']

[properties]
sys_root = '/usr/local/ps3dev'

[host_machine]
system = 'ps3'
cpu_family = 'ppc64'
cpu = 'cell'
endian = 'big'

[built-in options]
# C and CXX flags based on PPU_CFLAGS and PPU_CXXFLAGS
c_args = [
    '-mcpu=cell', '-mtune=cell', '-maltivec', '-mhard-float',
    '-fmodulo-sched', '-ffunction-sections', '-fdata-sections',
    '-I/usr/local/ps3dev/ppu/include', 
    '-I/usr/local/ps3dev/portlibs/ppu/include', 
    '-I/usr/local/ps3dev/ppu/include/simdmath',
    '-fomit-frame-pointer', '-fstrict-aliasing', '-funroll-loops', 
    '-ftree-vectorize', '-ffast-math'
  ]

cpp_args = [
    '-mcpu=cell', '-mtune=cell', '-maltivec', '-mhard-float',
    '-fmodulo-sched', '-ffunction-sections', '-fdata-sections',
    '-I/usr/local/ps3dev/ppu/include', 
    '-I/usr/local/ps3dev/portlibs/ppu/include', 
    '-I/usr/local/ps3dev/ppu/include/simdmath',
    '-fomit-frame-pointer', '-fstrict-aliasing', '-funroll-loops', 
    '-ftree-vectorize', '-ffast-math',
    '-D_GLIBCXX11_USE_C99_STDIO'
  ]

# Linker flags based on PPU_LDFLAGS
c_link_args = [
    '-mhard-float', '-fmodulo-sched', '-Wl,--gc-sections',
    '-L/usr/local/ps3dev/ppu/lib', 
    '-L/usr/local/ps3dev/portlibs/ppu/lib'
  ]

cpp_link_args = [
    '-mhard-float', '-fmodulo-sched', '-Wl,--gc-sections',
    '-L/usr/local/ps3dev/ppu/lib', 
    '-L/usr/local/ps3dev/portlibs/ppu/lib'
  ]
